# Generated by Django 5.2.8 on 2025-12-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
