# Generated by Django 5.2.8 on 2025-12-30 10:05

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    AdminSetting = apps.get_model("shop", "AdminSetting")
    if not AdminSetting.objects.exists():
        AdminSetting.objects.create(site_name="Surgical Mart Nepal")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_parent_brand_product_brand_and_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Surgical Mart', max_length=150)),
                ('default_meta_title', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.TextField(blank=True)),
                ('default_meta_keywords', models.CharField(blank=True, max_length=255)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_default_settings, migrations.RunPython.noop),
    ]
