# Generated by Django 5.2.8 on 2025-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='admin_notification_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='admin_notification_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='notify_admin_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='notify_admin_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='notify_customer_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='notify_customer_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='whatsapp_api_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='whatsapp_api_url',
            field=models.URLField(blank=True),
        ),
    ]
