# Generated by Django 5.2.8 on 2025-12-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_invoice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier_name'], name='shop_order_courier_39c7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='shop_order_tracking_c8c40f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipped_at'], name='shop_order_shipped__eff58b_idx'),
        ),
    ]
