# Generated by Django 5.2.8 on 2026-01-08 07:58

import uuid
from django.db import migrations, models


def _generate_order_number():
    return f"SMN-{uuid.uuid4().hex[:10].upper()}"


def populate_order_numbers_and_statuses(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    Audit = apps.get_model('shop', 'OrderStatusAuditLog')

    for order in Order.objects.all():
        updated_fields = []
        if not getattr(order, "order_number", None):
            order.order_number = f"SMN-{uuid.uuid4().hex[:10].upper()}"
            updated_fields.append("order_number")

        status_val = (order.status or "").upper()
        if status_val == "PACKED":
            status_val = "SHIPPED"
        if status_val and status_val != order.status:
            order.status = status_val
            updated_fields.append("status")

        payment_val = (order.payment_status or "").upper()
        if payment_val == "CONFIRMED":
            payment_val = "PAID"
        if payment_val and payment_val != order.payment_status:
            order.payment_status = payment_val
            updated_fields.append("payment_status")

        if updated_fields:
            order.save(update_fields=updated_fields)

    for audit in Audit.objects.all():
        changed = False
        if audit.from_status == "PACKED":
            audit.from_status = "SHIPPED"
            changed = True
        if audit.to_status == "PACKED":
            audit.to_status = "SHIPPED"
            changed = True
        if changed:
            audit.save(update_fields=["from_status", "to_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_brand_status_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=_generate_order_number, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('link_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_brands', models.ManyToManyField(blank=True, related_name='homepage_featured_brands', to='shop.brand')),
                ('featured_categories', models.ManyToManyField(blank=True, related_name='homepage_featured_categories', to='shop.category')),
                ('new_arrivals', models.ManyToManyField(blank=True, related_name='homepage_new_arrivals', to='shop.product')),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='shop_order_order_numb_idx'),
        ),
        migrations.AddIndex(
            model_name='heroslide',
            index=models.Index(fields=['order'], name='shop_heros_order_idx'),
        ),
        migrations.AddIndex(
            model_name='heroslide',
            index=models.Index(fields=['is_active'], name='shop_heros_is_acti_idx'),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='from_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusauditlog',
            name='to_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
        migrations.RunPython(populate_order_numbers_and_statuses, migrations.RunPython.noop),
    ]
