# Generated by Django 5.2.8 on 2026-01-08 08:01

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders_homepage_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brand',
            new_name='shop_brand_slug_5e71ec_idx',
            old_name='shop_brand_slug_10ae5a_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_slug_5ac49f_idx',
            old_name='shop_catego_slug_eb2071_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_parent__bb774a_idx',
            old_name='shop_catego_parent_4d19e8_idx',
        ),
        migrations.RenameIndex(
            model_name='heroslide',
            new_name='shop_herosl_order_08bb94_idx',
            old_name='shop_heros_order_idx',
        ),
        migrations.RenameIndex(
            model_name='heroslide',
            new_name='shop_herosl_is_acti_6b9714_idx',
            old_name='shop_heros_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='shop_invoic_number_93cb80_idx',
            old_name='shop_invoic_number_566897_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='shop_invoic_order_i_9cb916_idx',
            old_name='shop_invoic_order_i_638de2_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_order_n_db1214_idx',
            old_name='shop_order_order_numb_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_payment_201933_idx',
            old_name='shop_order_payment_628ba0_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_courier_541283_idx',
            old_name='shop_order_courier_39c7d6_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_trackin_b2d93f_idx',
            old_name='shop_order_tracking_c8c40f_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_shipped_261373_idx',
            old_name='shop_order_shipped__eff58b_idx',
        ),
        migrations.RenameIndex(
            model_name='orderadminnote',
            new_name='shop_ordera_order_i_d54357_idx',
            old_name='shop_order_order_c_b5c72c_idx',
        ),
        migrations.RenameIndex(
            model_name='orderadminnote',
            new_name='shop_ordera_order_i_43597c_idx',
            old_name='shop_order_order_i_12b4c8_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatusauditlog',
            new_name='shop_orders_order_i_eac08e_idx',
            old_name='shop_order_order_i_d99971_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatusauditlog',
            new_name='shop_orders_from_st_20b1c4_idx',
            old_name='shop_order_from_st_d2c42a_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatusauditlog',
            new_name='shop_orders_to_stat_b75b50_idx',
            old_name='shop_order_to_stat_601a0f_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=shop.models.Order._default_order_number, editable=False, max_length=32, unique=True),
        ),
    ]
