# Generated by Django 5.2.8 on 2025-11-20 06:35

import core.models.brand
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.brand.brand_image_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to hide brand from frontend')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_brand_slug_bb0dea_idx'), models.Index(fields=['name'], name='core_brand_name_92371f_idx')],
            },
        ),
    ]
